SELECT "속성명" FROM "표준데이터시트_고정";
UPDATE "표준데이터시트_고정" SET "속성명" = "CONSTRUCTION PER SHELL TUBE OUTER DIAMETER" WHERE "속성명" = "CONSTRUCTION PER SHELL OUTER DIAMETER";
UPDATE "표준데이터시트_고정" SET "속성명" = "CONSTRUCTION PER SHELL TUBE THICKNESS" WHERE "속성명" = "CONSTRUCTION PER SHELL THICKNESS";
UPDATE "표준데이터시트_고정" SET "속성명" = "CONSTRUCTION PER SHELL TUBE PITCH" WHERE "속성명" = "CONSTRUCTION PER SHELL PITCH";
UPDATE "표준데이터시트_고정" SET "속성명" = "CONSTRUCTION PER SHELL TUBE LENGTH" WHERE "속성명" = "CONSTRUCTION PER SHELL LENGTH";
UPDATE "표준데이터시트_고정" SET "속성명" = "CONSTRUCTION PER SHELL TUBE TYPE" WHERE "속성명" = "CONSTRUCTION PER SHELL TYPE";
